<Geral>:
    orientation: 'vertical'
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    ScreenManager:
        id: gerenciador_telas_principal
        size_hint_y: 0.9
        Screen:
            name: "menu"
            BoxLayout:
                orientation: 'vertical'
                spacing: 20
                padding: 30
                Image:
                    source: "imagens/vida_de_boneca.png"
                    Button:
                        background_color: 0, 0, 0, 0
                        pos: self.parent.pos
                        size: self.parent.size
                        on_release: app.root.janela_admin()

                BoxLayout:
                    orientation: 'vertical'
                    canvas.before:
                        Color:
                            rgba: 1, 97/255, 178/255, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [50,]
                    Label:
                        size_hint_y: 0.15
                        text: "Próximas entregas"
                        halign: "left"
                        font_size: 50
                        bold: True

                    ScrollView:
                        bar_color: 0, 0, 0, 0
                        Menu_proximas_entregas:
                            id: menu_proximas_entregas
                            spacing: 30
                            padding: 30
                            size_hint_x: None
                            width: self.minimum_width

                BoxLayout:
                    orientation: 'vertical'
                    canvas.before:
                        Color:
                            rgba: 1, 97/255, 178/255, 1
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [50,]
                    Label:
                        size_hint_y: 0.15
                        text: "Próximas feiras"
                        halign: "left"
                        font_size: 50
                        bold: True

                    ScrollView:
                        bar_color: 0, 0, 0, 0
                        Menu_proximas_feiras:
                            id: menu_proximas_feiras
                            spacing: 30
                            padding: 30
                            size_hint_x: None
                            width: self.minimum_width

        Screen:
            name: "administrador"
            BoxLayout:
                orientation: "vertical"
                spacing: 20
                padding: 20
                Label:
                    id: administrador_mensagens
                    size_hint_y: 0.1
                    bold: True
                    font_size: 40
                    color: 0, 0, 0, 1

                BoxLayout:
                    Button:
                        text: "JSON -> SQL"
                        on_release: app.root.json_to_sql()
                    
                    Button:
                        text: "SQL -> JSON"
                        on_release: app.root.sql_to_json()

                BoxLayout:
                    Button:
                        text: "Copiar JSON"
                        on_release: app.root.copiar_json()

                BoxLayout:
                    TextInput:
                        id: salvar_json
                        hint_text: "Salvar JSON"

                    Button:
                        text: "Salvar JSON"
                        on_release: app.root.salvar_json(salvar_json.text)

        Screen:
            name: "estoque"
            ScreenManager:
                id: gerenciador_colecoes
                Screen:
                    name: "mostrar colecoes"
                    on_enter: total_colecao.text = "TOTAL: R$" + "{:,.2f}".format(scroll_colecoes.preco_total())
                    BoxLayout:
                        spacing: 10
                        orientation: "vertical"
                        Button:
                            id: total_colecao
                            size_hint_y: 0.1
                            bold: True
                            italic: True
                            text: "TOTAL: R$" + "{:,.2f}".format(scroll_colecoes.preco_total())
                            color: 1, 1, 1, 1
                            background_color: 0, 0, 0, 0
                            font_size: 80
                            on_release: 
                                self.text = "TOTAL: R$" + "{:,.2f}".format(scroll_colecoes.preco_total())
                            canvas.before:
                                Color:
                                    rgba: 1, 36/255, 148/255, 1
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                            
                        BoxLayout:
                            size_hint_y: None
                            height: 70
                            BoxLayout:
                                size_hint_x: 0.1

                            TextInput:
                                id: pesquisar_colecao
                                hint_text: "Pesquisar colecão"
                                size_hint_x: 0.6
                                multiline: False
                                on_text_validate: 
                                    scroll_colecoes.pesquisar(self.text)

                                halign: "center"
                                background_color: 0, 0, 0, 0
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5
                            
                            Button:
                                size_hint_x: 0.2
                                background_color: 0, 0, 0, 0
                                color: 0.7, 0, 0, 1
                                text: "Limpar"
                                bold: True
                                on_release: 
                                    pesquisar_colecao.text = ""
                                    scroll_colecoes.atualizar()

                            BoxLayout:
                                size_hint_x: 0.1
                                
                        ScrollView:
                            size_hint_y: 0.8
                            bar_color: 0, 0, 0, 0
                            Scroll_colecoes:
                                id: scroll_colecoes
                                orientation: 'vertical'
                                spacing: 30
                                padding: 30
                                size_hint_y: None
                                height: self.minimum_height

                                Button:
                                    size_hint: None, None
                                    height: 150
                                    on_release: 
                                        gerenciador_colecoes.transition.direction = "down"
                                        gerenciador_colecoes.current = "adicionar colecoes"
                                    bold: True
                                    width: self.parent.width - self.parent.padding[0] * 2
                                    x: 0
                                    text: "+"
                                    background_color: (0, 0, 0, 0)
                                    color: (1, 1, 1, 1)
                                    font_size: 120
                                    canvas.before:
                                        Color:
                                            rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                        RoundedRectangle:
                                            pos: self.pos
                                            size: self.size
                                            radius: [30,]
                
                Screen:
                    on_enter:
                        adicionar_colecoes_texto.text = ""

                    name: "adicionar colecoes"
                    BoxLayout:
                        orientation: 'vertical'
                        BoxLayout:
                            size_hint_y: 0.85
                            padding: 50, 150, 50, 150
                            TextInput:
                                size_hint_y: None
                                height: self.font_size + 30
                                y: (self.parent.height - self.height) // 2
                                id: adicionar_colecoes_texto
                                hint_text: "Nome da coleção"
                                text: ""
                                multiline: False
                                halign: "center"
                                font_size: 80
                                background_color: 0, 0, 0, 0
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5

                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_colecoes.transition.direction = "up"
                                    gerenciador_colecoes.current = "mostrar colecoes"

                            Botao:
                                text: "Adicionar"
                                on_release:
                                    gerenciador_colecoes.transition.direction = "up"
                                    if adicionar_colecoes_texto.text != "": gerenciador_colecoes.current = "mostrar colecoes"
                                    if adicionar_colecoes_texto.text != "": scroll_colecoes.adicionar_colecao(adicionar_colecoes_texto.text)
                
                Screen:
                    name: "editar colecoes"
                    BoxLayout:
                        orientation: 'vertical'
                        BoxLayout:
                            size_hint_y: 0.85
                            padding: 50, 150, 50, 150
                            TextInput:
                                size_hint_y: None
                                height: self.font_size + 30
                                y: (self.parent.height - self.height) // 2
                                id: editar_colecoes_texto
                                hint_text: "Nome da coleção"
                                text: ""
                                multiline: False
                                halign: "center"
                                font_size: 80
                                background_color: 0, 0, 0, 0
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5

                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_colecoes.transition.direction = "up"
                                    gerenciador_colecoes.current = "mostrar colecoes"

                            Botao:
                                text: "Excluir"
                                on_release: 
                                    gerenciador_colecoes.transition.direction = "up"
                                    scroll_colecoes.excluir_colecao()
                                    gerenciador_colecoes.current = "mostrar colecoes"

                            Botao:
                                text: "Concluir"
                                on_release:
                                    gerenciador_colecoes.transition.direction = "up"
                                    if editar_colecoes_texto.text != "": gerenciador_colecoes.current = "mostrar colecoes"
                                    if editar_colecoes_texto.text != "": scroll_colecoes.editar_colecao(editar_colecoes_texto.text)

                Screen:
                    name: "tela produtos"
                    ScreenManager:
                        id: gerenciador_produtos
                        Screen:
                            name: "mostrar produtos"
                            on_enter: total_produto.text = "TOTAL: R$" + "{:,.2f}".format(scroll_produtos.preco_total())
                            BoxLayout:
                                spacing: 10
                                orientation: "vertical"
                                Button:
                                    id: total_produto
                                    size_hint_y: 0.1
                                    bold: True
                                    italic: True
                                    text: "TOTAL: R$" + "{:,.2f}".format(scroll_produtos.preco_total())
                                    color: 1, 1, 1, 1
                                    background_color: 0, 0, 0, 0
                                    font_size: 80
                                    on_release: 
                                        self.text = "TOTAL: R$" + "{:,.2f}".format(scroll_produtos.preco_total())
                                    canvas.before:
                                        Color:
                                            rgba: 1, 36/255, 148/255, 1
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                    
                                BoxLayout:
                                    size_hint_y: None
                                    height: 70
                                    BoxLayout:
                                        size_hint_x: 0.1

                                    TextInput:
                                        id: pesquisar_produtos
                                        hint_text: "Pesquisar em "
                                        size_hint_x: 0.6
                                        multiline: False
                                        on_text_validate: 
                                            scroll_produtos.pesquisar(self.text)

                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5
                                    
                                    Button:
                                        size_hint_x: 0.2
                                        background_color: 0, 0, 0, 0
                                        color: 0.7, 0, 0, 1
                                        text: "Limpar"
                                        bold: True
                                        on_release: 
                                            pesquisar_produtos.text = ""
                                            scroll_produtos.atualizar()

                                    BoxLayout:
                                        size_hint_x: 0.1
                                        
                                ScrollView:
                                    size_hint_y: 0.8
                                    bar_color: 0, 0, 0, 0
                                    Scroll_produtos:
                                        id: scroll_produtos
                                        orientation: 'vertical'
                                        spacing: 30
                                        padding: 30
                                        size_hint_y: None
                                        height: self.minimum_height

                                        Button:
                                            size_hint: None, None
                                            height: 150
                                            on_release: 
                                                gerenciador_produtos.transition.direction = "down"
                                                gerenciador_produtos.current = "adicionar produtos"
                                            bold: True
                                            width: self.parent.width - self.parent.padding[0] * 2
                                            x: 0
                                            text: "+"
                                            background_color: (0, 0, 0, 0)
                                            color: (1, 1, 1, 1)
                                            font_size: 120
                                            canvas.before:
                                                Color:
                                                    rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                                RoundedRectangle:
                                                    pos: self.pos
                                                    size: self.size
                                                    radius: [30,]

                        Screen:
                            on_enter:
                                adicionar_produto_imagem.source = "imagens/logo.png"
                                adicionar_produto_nome.text = ""
                                adicionar_produto_preco.text = ""

                            name: "adicionar produtos"
                            BoxLayout:
                                orientation: "vertical"
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: 20
                                    spacing: 15
                                    Label:
                                        size_hint_y: 0.15
                                        text: "Escolha uma imagem"
                                        bold: True
                                        color: 0, 0, 0, 1
                                        font_size: 80

                                    AsyncImage:
                                        id: adicionar_produto_imagem
                                        source: "imagens/logo.png"
                                        Button:
                                            size: self.parent.size
                                            pos: self.parent.pos
                                            background_color: 0, 0, 0, 0
                                            on_release: 
                                                app.root.file_chooser(gerenciador_produtos.current)

                                    TextInput:
                                        id: adicionar_produto_nome
                                        font_size: 80
                                        text: ""
                                        hint_text: "Nome do produto"
                                        multiline: False
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                width: 5

                                    TextInput:
                                        id: adicionar_produto_preco
                                        font_size: 80
                                        text: ""
                                        input_type: 'number'
                                        input_filter: 'int'
                                        hint_text: "Preço do produto"
                                        multiline: False
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                width: 5

                                BoxLayout:
                                    size_hint_y: 0.15
                                    Botao:
                                        text: "Voltar"
                                        on_release: 
                                            gerenciador_produtos.transition.direction = "up"
                                            gerenciador_produtos.current = "mostrar produtos"

                                    Botao:
                                        text: "Adicionar"
                                        on_release: 
                                            gerenciador_produtos.transition.direction = "up"
                                            if adicionar_produto_nome.text != "" and adicionar_produto_preco.text != "": gerenciador_produtos.current = "mostrar produtos"
                                            if adicionar_produto_nome.text != "" and adicionar_produto_preco.text != "": scroll_produtos.adicionar_produto(adicionar_produto_imagem.source, adicionar_produto_nome.text, adicionar_produto_preco.text)

                        Screen:
                            name: "editar produtos"
                            BoxLayout:
                                orientation: "vertical"
                                BoxLayout:
                                    orientation: 'vertical'
                                    padding: 20
                                    spacing: 15
                                    Label:
                                        size_hint_y: 0.15
                                        text: "Escolha uma imagem"
                                        bold: True
                                        color: 0, 0, 0, 1
                                        font_size: 80

                                    AsyncImage:
                                        id: editar_produto_imagem
                                        source: "imagens/logo.png"
                                        size: self.parent.size
                                        pos: self.parent.pos
                                        Button:
                                            size: self.parent.size
                                            pos: self.parent.pos
                                            background_color: 0, 0, 0, 0
                                            on_release: 
                                                app.root.file_chooser(gerenciador_produtos.current)

                                    TextInput:
                                        id: editar_produto_nome
                                        font_size: 80
                                        text: ""
                                        hint_text: "Nome do produto"
                                        multiline: False
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                width: 5

                                    TextInput:
                                        id: editar_produto_preco
                                        font_size: 80
                                        text: ""
                                        input_type: 'number'
                                        input_filter: 'int'
                                        hint_text: "Preço do produto"
                                        multiline: False
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                width: 5

                                BoxLayout:
                                    size_hint_y: 0.15
                                    Botao:
                                        text: "Voltar"
                                        on_release: 
                                            gerenciador_produtos.transition.direction = "up"
                                            gerenciador_produtos.current = "mostrar produtos"

                                    Botao:
                                        text: "Excluir"
                                        on_release: 
                                            gerenciador_produtos.transition.direction = "up"
                                            gerenciador_produtos.current = "mostrar produtos"
                                            scroll_produtos.excluir_produto()

                                    Botao:
                                        text: "Concluir"
                                        on_release: 
                                            gerenciador_produtos.transition.direction = "up"
                                            if editar_produto_nome.text != "" and editar_produto_preco.text != "": scroll_produtos.editar_produto(editar_produto_imagem.source, editar_produto_nome.text, editar_produto_preco.text)
                                            if editar_produto_nome.text != "" and editar_produto_preco.text != "": gerenciador_produtos.current = "mostrar produtos"

                        Screen:
                            name: "tela subprodutos"
                            ScreenManager:
                                id: gerenciador_subprodutos
                                Screen:
                                    name: "mostrar subprodutos"
                                    on_pre_enter: total_subproduto.text = "TOTAL: R$" + "{:,.2f}".format(scroll_subprodutos.preco_total())
                                    BoxLayout:
                                        spacing: 10
                                        orientation: "vertical"
                                        Button:
                                            id: total_subproduto
                                            size_hint_y: 0.1
                                            bold: True
                                            italic: True
                                            text: "TOTAL: R$" + "{:,.2f}".format(scroll_subprodutos.preco_total())
                                            color: 1, 1, 1, 1
                                            background_color: 0, 0, 0, 0
                                            font_size: 80
                                            on_release: 
                                                self.text = "TOTAL: R$" + "{:,.2f}".format(scroll_subprodutos.preco_total())
                                            canvas.before:
                                                Color:
                                                    rgba: 1, 36/255, 148/255, 1
                                                Rectangle:
                                                    pos: self.pos
                                                    size: self.size
                                            
                                        BoxLayout:
                                            size_hint_y: None
                                            height: 70
                                            BoxLayout:
                                                size_hint_x: 0.1

                                            TextInput:
                                                id: pesquisar_subprodutos
                                                hint_text: "Pesquisar subproduto"
                                                size_hint_x: 0.6
                                                multiline: False
                                                on_text_validate: 
                                                    scroll_subprodutos.pesquisar(self.text)

                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y, self.width, self.height)
                                                        width: 5
                                            
                                            Button:
                                                size_hint_x: 0.2
                                                background_color: 0, 0, 0, 0
                                                color: 0.7, 0, 0, 1
                                                text: "Limpar"
                                                bold: True
                                                on_release: 
                                                    pesquisar_subprodutos.text = ""
                                                    scroll_subprodutos.atualizar()

                                            BoxLayout:
                                                size_hint_x: 0.1
                                                
                                        ScrollView:
                                            size_hint_y: 0.8
                                            bar_color: 0, 0, 0, 0
                                            Scroll_subprodutos:
                                                id: scroll_subprodutos
                                                orientation: 'vertical'
                                                spacing: 30
                                                padding: 30
                                                size_hint_y: None
                                                height: self.minimum_height

                                                Button:
                                                    size_hint: None, None
                                                    height: 150
                                                    on_release: 
                                                        gerenciador_subprodutos.transition.direction = "down"
                                                        gerenciador_subprodutos.current = "adicionar subprodutos"
                                                    bold: True
                                                    width: self.parent.width - self.parent.padding[0] * 2
                                                    x: 0
                                                    text: "+"
                                                    background_color: (0, 0, 0, 0)
                                                    color: (1, 1, 1, 1)
                                                    font_size: 120
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                                        RoundedRectangle:
                                                            pos: self.pos
                                                            size: self.size
                                                            radius: [30,]
                                
                                Screen:
                                    on_enter:
                                        adicionar_subproduto_quantidade.text = ""
                                        adicionar_subproduto_nome.text = ""
                                        adicionar_subproduto_imagem.source = "imagens/logo.png"
                                        
                                    name: "adicionar subprodutos"
                                    BoxLayout:
                                        orientation: "vertical"
                                        BoxLayout:
                                            orientation: 'vertical'
                                            padding: 20
                                            spacing: 15
                                            Label:
                                                size_hint_y: 0.15
                                                text: "Escolha uma imagem"
                                                bold: True
                                                color: 0, 0, 0, 1
                                                font_size: 80

                                            AsyncImage:
                                                id: adicionar_subproduto_imagem
                                                source: "imagens/logo.png"
                                                Button:
                                                    size: self.parent.size
                                                    pos: self.parent.pos
                                                    background_color: 0, 0, 0, 0
                                                    on_release: 
                                                        app.root.file_chooser(gerenciador_subprodutos.current)

                                            TextInput:
                                                id: adicionar_subproduto_nome
                                                font_size: 80
                                                text: ""
                                                hint_text: "Nome do subproduto"
                                                multiline: False
                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                        width: 5

                                            TextInput:
                                                id: adicionar_subproduto_quantidade
                                                font_size: 80
                                                text: ""
                                                input_type: 'number'
                                                input_filter: 'int'
                                                hint_text: "Quantidade do subproduto"
                                                multiline: False
                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                        width: 5

                                        BoxLayout:
                                            size_hint_y: 0.15
                                            Botao:
                                                text: "Voltar"
                                                on_release: 
                                                    gerenciador_subprodutos.transition.direction = "up"
                                                    gerenciador_subprodutos.current = "mostrar subprodutos"

                                            Botao:
                                                text: "Adicionar"
                                                on_release: 
                                                    gerenciador_subprodutos.transition.direction = "up"
                                                    if adicionar_subproduto_nome.text != "" and adicionar_subproduto_quantidade.text != "": gerenciador_subprodutos.current = "mostrar subprodutos"
                                                    if adicionar_subproduto_nome.text != "" and adicionar_subproduto_quantidade.text != "": scroll_subprodutos.adicionar_subproduto(adicionar_subproduto_imagem.source, adicionar_subproduto_nome.text, adicionar_subproduto_quantidade.text)
            
                                    
                                Screen:
                                    name: "editar subprodutos"
                                    BoxLayout:
                                        orientation: "vertical"
                                        BoxLayout:
                                            orientation: 'vertical'
                                            padding: 20
                                            spacing: 15
                                            Label:
                                                size_hint_y: 0.15
                                                text: "Escolha uma imagem"
                                                bold: True
                                                color: 0, 0, 0, 1
                                                font_size: 80

                                            AsyncImage:
                                                id: editar_subproduto_imagem
                                                source: "imagens/logo.png"
                                                Button:
                                                    size: self.parent.size
                                                    pos: self.parent.pos
                                                    background_color: 0, 0, 0, 0
                                                    on_release: 
                                                        app.root.file_chooser(gerenciador_subprodutos.current)

                                            TextInput:
                                                id: editar_subproduto_nome
                                                font_size: 80
                                                text: ""
                                                hint_text: "Nome do subproduto"
                                                multiline: False
                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                        width: 5

                                            TextInput:
                                                id: editar_subproduto_quantidade
                                                font_size: 80
                                                text: ""
                                                input_type: 'number'
                                                input_filter: 'int'
                                                hint_text: "Quantidade do subproduto"
                                                multiline: False
                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y + self.height - self.font_size - 30 - 10, self.width, self.font_size + 30)
                                                        width: 5

                                        BoxLayout:
                                            size_hint_y: 0.15
                                            Botao:
                                                text: "Voltar"
                                                on_release: 
                                                    gerenciador_subprodutos.current = "mostrar subprodutos"

                                            Botao:
                                                text: "Excluir"
                                                on_release: 
                                                    gerenciador_subprodutos.transition.direction = "up"
                                                    gerenciador_subprodutos.current = "mostrar subprodutos"
                                                    scroll_subprodutos.excluir_subproduto()

                                            Botao:
                                                text: "Concluir"
                                                on_release: 
                                                    gerenciador_subprodutos.transition.direction = "up"
                                                    if editar_subproduto_nome.text != "" and editar_subproduto_quantidade.text != "": gerenciador_subprodutos.current = "mostrar subprodutos"
                                                    if editar_subproduto_nome.text != "" and editar_subproduto_quantidade.text != "": scroll_subprodutos.editar_subproduto(editar_subproduto_imagem.source, editar_subproduto_nome.text, editar_subproduto_quantidade.text)

                                Screen:
                                    name: "imagens subprodutos"
                                    BoxLayout:
                                        ScrollView:
                                            bar_color: 0, 0, 0, 0
                                            Scroll_imagens_subprodutos:
                                                orientation: 'vertical'
                                                spacing: 30
                                                padding: 30
                                                size_hint_y: None
                                                height: self.minimum_height
                                                id: scroll_imagens_subprodutos

                                                Button:
                                                    size_hint: None, None
                                                    height: 150
                                                    on_release: scroll_imagens_subprodutos.copiar_todas_as_imagens()
                                                    bold: True
                                                    width: self.parent.width - self.parent.padding[0] * 2
                                                    x: 0
                                                    text: "Copiar imagens"
                                                    background_color: (0, 0, 0, 0)
                                                    color: (1, 1, 1, 1)
                                                    font_size: 80
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                                        RoundedRectangle:
                                                            pos: self.pos
                                                            size: self.size
                                                            radius: [30,]

                                                Button:
                                                    size_hint: None, None
                                                    height: 150
                                                    on_release: app.root.file_chooser("imagens subprodutos")
                                                    bold: True
                                                    width: self.parent.width - self.parent.padding[0] * 2
                                                    x: 0
                                                    text: "+"
                                                    background_color: (0, 0, 0, 0)
                                                    color: (1, 1, 1, 1)
                                                    font_size: 120
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                                        RoundedRectangle:
                                                            pos: self.pos
                                                            size: self.size
                                                            radius: [30,]

        Screen:
            name: "feiras"
            ScreenManager:
                id: gerenciador_feiras
                Screen:
                    name: "scroll_feiras_principal"
                    ScrollView:
                        bar_color: 0, 0, 0, 0
                        Feiras_scroll:
                            id: feiras_scroll
                            orientation: "vertical"
                            padding: 30
                            spacing: 30
                            size_hint_y: None
                            height: self.minimum_height
                        
                            Button:
                                size_hint: None, None
                                height: 150
                                on_release: 
                                    gerenciador_feiras.transition.direction = "down"
                                    gerenciador_feiras.current = "adicionar"
                                bold: True
                                width: self.parent.width - self.parent.padding[0] * 2
                                x: 0
                                text: "+"
                                background_color: (0, 0, 0, 0)
                                color: (1, 1, 1, 1)
                                font_size: 120
                                canvas.before:
                                    Color:
                                        rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [30,]

                Screen:
                    name: "adicionar subproduto"
                    on_enter: 
                        spinner_feira_adicionar_colecao.values = feiras_scroll.colecoes()
                        spinner_feira_adicionar_colecao.text = "•Escolha uma coleção"
                        spinner_feira_adicionar_produto.text = "•Escolha um produto"
                        spinner_feira_adicionar_subproduto.text = "•Escolha um subproduto"
                        quantidade_subproduto_feiras_adicionar.text = ""

                    BoxLayout:
                        orientation: "vertical"
                        BoxLayout:
                            orientation: "vertical"
                            size_hint_y: 0.85
                            padding: 30
                            spacing: 40
                            BoxLayout:
                                orientation: "vertical"

                            SpinnerDropdown:
                                id: spinner_feira_adicionar_colecao
                                text: "•Escolha uma coleção"
                                background_color: 0, 0, 0, 0
                                font_size: 70
                                color: 0, 0, 0, 1
                                values: feiras_scroll.colecoes()
                                on_text: spinner_feira_adicionar_produto.values = feiras_scroll.procurar_produtos(self.text)

                            SpinnerDropdown:
                                id: spinner_feira_adicionar_produto
                                text: "•Escolha um produto"
                                background_color: 0, 0, 0, 0
                                font_size: 70
                                color: 0, 0, 0, 1
                                on_text: spinner_feira_adicionar_subproduto.values = feiras_scroll.procurar_subprodutos(self.text)
                                
                            SpinnerDropdown:
                                id: spinner_feira_adicionar_subproduto
                                text: "•Escolha um subproduto"
                                background_color: 0, 0, 0, 0
                                font_size: 70
                                color: 0, 0, 0, 1
                                
                            BoxLayout:
                                orientation: "vertical"
                                spacing: 20
                                BoxLayout:
                                    TextInput:
                                        id: quantidade_subproduto_feiras_adicionar
                                        input_filter: "float"
                                        background_color: 0, 0, 0, 0
                                        hint_text: "Quantidade"
                                        font_size: 70
                                        height: 100
                                        size_hint_x: 0.5
                                        size_hint_y: None
                                        halign: "center"
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5
                                BoxLayout:
                                BoxLayout:

                        
                        BoxLayout:
                            size_hint_y: 0.15
                            Button:
                                text: "Voltar"
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                font_size: 80
                                bold: True
                                on_release: 
                                    gerenciador_feiras.transition.direction = "up"
                                    gerenciador_feiras.current = "scroll_feiras_principal"
                            
                            Button:
                                text: "Adicionar"
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                font_size: 80
                                bold: True
                                on_release: 
                                    gerenciador_feiras.transition.direction = "up"
                                    if spinner_feira_adicionar_subproduto.text != "•Escolha um subproduto" and quantidade_subproduto_feiras_adicionar.text.isnumeric(): gerenciador_feiras.current = "scroll_feiras_principal"
                                    if spinner_feira_adicionar_subproduto.text != "•Escolha um subproduto" and quantidade_subproduto_feiras_adicionar.text.isnumeric(): feiras_scroll.adicionar_produto(spinner_feira_adicionar_subproduto.text, quantidade_subproduto_feiras_adicionar.text)
                

                Screen:
                    name: "adicionar"
                    BoxLayout:
                        orientation: "vertical"
                        BoxLayout:
                            orientation: "vertical"
                            spacing: 30
                            padding: 30
                            TextInput:
                                id: nome_feira_adicionar
                                background_color: 0, 0, 0, 0
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                hint_text: "Nome da feira"
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5
                            
                            TextInput:
                                id: local_feira_adicionar
                                background_color: 0, 0, 0, 0
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                hint_text: "Local da feira"
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5
                            
                            TextInput:
                                id: descricao_feira_adicionar
                                background_color: 0, 0, 0, 0
                                hint_text: "Descrição"
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5

                        BoxLayout:
                            padding: 30
                            SpinnerDropdown:
                                id: dia_feira_adicionar
                                font_size: 70
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                text: "•Dia"
                                values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
                            
                            SpinnerDropdown:
                                id: mes_feira_adicionar
                                text: "•Mês"
                                font_size: 70
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
                            
                            SpinnerDropdown:
                                id: ano_feira_adicionar
                                font_size: 70
                                text: "•Ano"
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                values: agenda_scroll.anos

                        BoxLayout:
                            orientation: "vertical"
                            BoxLayout:
                                padding: 30
                                spacing: 15
                                TextInput:
                                    id: horario_inicial_feira_adicionar
                                    hint_text: "Horário inicial"
                                    halign: "center"
                                    size_hint_y: None
                                    height: 100
                                    font_size: 70
                                    background_color: 0, 0, 0, 0
                                    canvas.before:
                                        Color:
                                            rgba: 0, 0, 0, 1
                                        Line:
                                            rectangle: (self.x, self.y, self.width, self.height)
                                            width: 5
                                TextInput:
                                    id: horario_final_feira_adicionar
                                    background_color: 0, 0, 0, 0
                                    hint_text: "Horário final"
                                    halign: "center"
                                    size_hint_y: None
                                    height: 100
                                    font_size: 70
                                    canvas.before:
                                        Color:
                                            rgba: 0, 0, 0, 1
                                        Line:
                                            rectangle: (self.x, self.y, self.width, self.height)
                                            width: 5

                            BoxLayout:
                        
                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_feiras.current = "scroll_feiras_principal"
                                    gerenciador_feiras.transition.direction = "up"
                            Botao:
                                text: "Concluir"
                                on_release: 
                                    gerenciador_feiras.transition.direction = "up"
                                    if dia_feira_adicionar.text.isnumeric() and mes_feira_adicionar.text.isnumeric() and ano_feira_adicionar.text.isnumeric(): feiras_scroll.adicionar(dia_feira_adicionar.text, mes_feira_adicionar.text, ano_feira_adicionar.text, local_feira_adicionar.text, horario_inicial_feira_adicionar.text, horario_final_feira_adicionar.text, descricao_feira_adicionar.text, nome_feira_adicionar.text)
                                    if dia_feira_adicionar.text.isnumeric() and mes_feira_adicionar.text.isnumeric() and ano_feira_adicionar.text.isnumeric(): gerenciador_feiras.current = "scroll_feiras_principal"


                Screen:
                    name: "editar"
                    BoxLayout:
                        orientation: "vertical"
                        BoxLayout:
                            orientation: "vertical"
                            spacing: 30
                            padding: 30
                            TextInput:
                                id: nome_feira_editar
                                background_color: 0, 0, 0, 0
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                hint_text: "Nome da feira"
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5
                            
                            TextInput:
                                id: local_feira_editar
                                background_color: 0, 0, 0, 0
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                hint_text: "Local da feira"
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5
                            
                            TextInput:
                                id: descricao_feira_editar
                                background_color: 0, 0, 0, 0
                                hint_text: "Descrição"
                                halign: "center"
                                size_hint_y: None
                                height: 100
                                font_size: 70
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5

                        BoxLayout:
                            padding: 30
                            SpinnerDropdown:
                                id: dia_feira_editar
                                font_size: 70
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                text: "•Dia"
                                values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
                            
                            SpinnerDropdown:
                                id: mes_feira_editar
                                text: "•Mês"
                                font_size: 70
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
                            
                            SpinnerDropdown:
                                id: ano_feira_editar
                                font_size: 70
                                text: "•Ano"
                                background_color: 0, 0, 0, 0
                                color: 0, 0, 0, 1
                                values: agenda_scroll.anos
                        BoxLayout:
                            orientation: "vertical"
                            BoxLayout:
                                padding: 30
                                spacing: 15
                                TextInput:
                                    id: horario_inicial_feira_editar
                                    hint_text: "Horário inicial"
                                    halign: "center"
                                    size_hint_y: None
                                    height: 100
                                    font_size: 70
                                    background_color: 0, 0, 0, 0
                                    canvas.before:
                                        Color:
                                            rgba: 0, 0, 0, 1
                                        Line:
                                            rectangle: (self.x, self.y, self.width, self.height)
                                            width: 5
                                TextInput:
                                    id: horario_final_feira_editar
                                    background_color: 0, 0, 0, 0
                                    hint_text: "Horário final"
                                    halign: "center"
                                    size_hint_y: None
                                    height: 100
                                    font_size: 70
                                    canvas.before:
                                        Color:
                                            rgba: 0, 0, 0, 1
                                        Line:
                                            rectangle: (self.x, self.y, self.width, self.height)
                                            width: 5

                            BoxLayout:

                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_feiras.current = "scroll_feiras_principal"
                                    gerenciador_feiras.transition.direction = "up"

                            Botao:
                                text: "Excluir"
                                on_release:
                                    gerenciador_feiras.transition.direction = "up"
                                    gerenciador_feiras.current = "scroll_feiras_principal"
                                    feiras_scroll.excluir()

                            Botao:
                                text: "Concluir"
                                on_release: 
                                    gerenciador_feiras.transition.direction = "up"
                                    if dia_feira_editar.text.isnumeric() and mes_feira_editar.text.isnumeric() and ano_feira_editar.text.isnumeric(): feiras_scroll.editar(dia_feira_editar.text, mes_feira_editar.text, ano_feira_editar.text, local_feira_editar.text, horario_inicial_feira_editar.text, horario_final_feira_editar.text, descricao_feira_editar.text, nome_feira_editar.text)
                                    if dia_feira_editar.text.isnumeric() and mes_feira_editar.text.isnumeric() and ano_feira_editar.text.isnumeric(): gerenciador_feiras.current = "scroll_feiras_principal"


                Screen:
                    name: "concluir feira"
                    on_enter: concluir_feira_scroll.atualizar()
                    ScreenManager:
                        id: gerenciador_concluir_feira
                        Screen:
                            name: "concluir feira principal"
                            BoxLayout:
                                orientation: "vertical"
                                Label:
                                    size_hint_y: 0.15
                                    font_size: 80
                                    color: 1, 1, 1, 1
                                    background_color: 1, 36/255, 148/255, 1
                                    canvas.before:
                                        Color:
                                            rgba: self.background_color
                                        Rectangle:
                                            pos: self.pos
                                            size: self.size
                                    text: "Coloque as vendas da feira"
                                    bold: True
                                BoxLayout:
                                    size_hint_y: 0.70
                                    ScrollView:
                                        bar_color: 0, 0, 0, 0
                                        Concluir_feira_scroll:
                                            id: concluir_feira_scroll
                                            orientation: "vertical"
                                            padding: 30
                                            spacing: 30
                                            size_hint_y: None
                                            height: self.minimum_height

                                            Button:
                                                size_hint: None, None
                                                on_release: 
                                                    gerenciador_concluir_feira.transition.direction = "left"
                                                    gerenciador_concluir_feira.current = "adicionar venda feira"
                                                bold: True
                                                width: self.parent.width - self.parent.padding[0] * 2
                                                x: 0
                                                height: 150
                                                text: "+"
                                                background_color: (0, 0, 0, 0)
                                                color: (1, 1, 1, 1)
                                                font_size: 120
                                                canvas.before:
                                                    Color:
                                                        rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                                    RoundedRectangle:
                                                        pos: self.pos
                                                        size: self.size
                                                        radius: [30,]
                        
                                BoxLayout:
                                    size_hint_y: 0.15
                                    Botao:
                                        text: "Voltar"
                                        on_release: 
                                            gerenciador_feiras.current = "scroll_feiras_principal"
                                            gerenciador_feiras.transition.direction = "up"
                                    Botao:
                                        text: "Concluir"
                                        on_release: 
                                            concluir_feira_scroll.concluir_feira()
                                            gerenciador_feiras.transition.direction = "up"
                                            gerenciador_feiras.current = "scroll_feiras_principal"
                                            feiras_scroll.atualizar()
                        
                        Screen:
                            name: "adicionar venda feira"
                            on_enter: 
                                spinner_feira_adicionar_subproduto_concluir.values = concluir_feira_scroll.subprodutos_levados_na_feira()
                                spinner_feira_adicionar_subproduto_concluir.text = "•Escolha um subproduto"
                                spinner_feiras_concluir_venda_pagamento.text = "•Método de pagamento"
                                quantidade_subproduto_feira_adicionar_concluir.text = ""
                                preco_subproduto_feira_adicionar_concluir.text = ""
                                descricao_feira_adicionar_concluir.text = ""
                            
                            BoxLayout:
                                orientation: "vertical"
                                size_hint_y: 0.85
                                padding: 30
                                spacing: 15
                                BoxLayout:
                                    size_hint_y: 0.55
                                    spacing: 15
                                    BoxLayout:
                                        orientation: "vertical"
                                        SpinnerDropdown:
                                            id: spinner_feira_adicionar_subproduto_concluir
                                            background_color: 0, 0, 0, 0
                                            font_size: 50
                                            text: "•Escolha um subproduto"
                                            color: 0, 0, 0, 1
                                            values: concluir_feira_scroll.subprodutos_levados_na_feira()
                                        SpinnerDropdown:
                                            id: spinner_feiras_concluir_venda_pagamento
                                            background_color: 0, 0, 0, 0
                                            font_size: 50
                                            color: 0, 0, 0, 1
                                            text: "•Método de pagamento"
                                            values: ["Pix", "Dinheiro físico", "Cartão de crédito", "Cartão de débito"]
                                        
                                    BoxLayout:
                                        spacing: 15
                                        orientation: "vertical"
                                        BoxLayout:
                                            TextInput:
                                                id: quantidade_subproduto_feira_adicionar_concluir
                                                input_filter: "float"
                                                hint_text: "Quantidade"
                                                size_hint_y: None
                                                font_size: 70
                                                center: self.parent.center
                                                height: 100
                                                halign: "center"
                                                background_color: 0, 0, 0, 0
                                                color: 0, 0, 0, 1
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y, self.width, self.height)
                                                        width: 5
                                        BoxLayout: 
                                            TextInput:
                                                id: preco_subproduto_feira_adicionar_concluir
                                                input_filter: "float"
                                                center: self.parent.center
                                                hint_text: "Preço"
                                                halign: "center"
                                                size_hint_y: None
                                                font_size: 70
                                                height: 100
                                                background_color: 0, 0, 0, 0
                                                color: 0, 0, 0, 1
                                                canvas.before:
                                                    Color:
                                                        rgba: 0, 0, 0, 1
                                                    Line:
                                                        rectangle: (self.x, self.y, self.width, self.height)
                                                        width: 5
                
                                BoxLayout:
                                    orientation: "vertical"
                                    size_hint_y: 0.3
                                    TextInput:
                                        id: descricao_feira_adicionar_concluir
                                        hint_text: "Descrição"
                                        size_hint_y: None
                                        font_size: 70
                                        height: 175
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        color: 0, 0, 0, 1
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5
                                    BoxLayout:
                                        size_hint_y: None
                                
                                BoxLayout:
                                    size_hint_y: 0.15
                                    Botao:
                                        text: "Voltar"
                                        on_release: 
                                            gerenciador_concluir_feira.current = "concluir feira principal"
                                            gerenciador_concluir_feira.transition.direction = "right"
                                    
                                    Botao:
                                        text: "Adicionar"
                                        on_release: 
                                            gerenciador_concluir_feira.transition.direction = "right"
                                            if spinner_feira_adicionar_subproduto_concluir.text != "Escolha um subproduto" and quantidade_subproduto_feira_adicionar_concluir.text.isnumeric() and preco_subproduto_feira_adicionar_concluir.text.isnumeric() and spinner_feiras_concluir_venda_pagamento.text != "Escolha o método de pagamento": gerenciador_concluir_feira.current = "concluir feira principal"
                                            if spinner_feira_adicionar_subproduto_concluir.text != "Escolha um subproduto" and quantidade_subproduto_feira_adicionar_concluir.text.isnumeric() and preco_subproduto_feira_adicionar_concluir.text.isnumeric() and spinner_feiras_concluir_venda_pagamento.text != "Escolha o método de pagamento": concluir_feira_scroll.adicionar(spinner_feira_adicionar_subproduto_concluir.text, quantidade_subproduto_feira_adicionar_concluir.text, descricao_feira_adicionar_concluir.text, preco_subproduto_feira_adicionar_concluir.text, spinner_feiras_concluir_venda_pagamento.text, feiras_scroll.finalizar_feiras)


        Screen:
            name: "agenda"
            ScreenManager:
                id: gerenciador_agenda
                Screen:
                    name: "principal"
                    ScrollView:
                        bar_color: 0, 0, 0, 0
                        Agenda_scroll:
                            id: agenda_scroll
                            orientation: "vertical"
                            size_hint_y: None
                            height: self.minimum_height
                            padding: 30
                            spacing: 30

                            Button:
                                nome: "Butao"
                                height: 150
                                size_hint: None, None
                                on_release: 
                                    gerenciador_agenda.transition.direction = "down"
                                    gerenciador_agenda.current = "adicionar"
                                bold: True
                                width: self.parent.width - self.parent.padding[0] * 2
                                x: 0
                                text: "+"
                                background_color: (0, 0, 0, 0)
                                color: (1, 1, 1, 1)
                                font_size: 120
                                canvas.before:
                                    Color:
                                        rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                                    RoundedRectangle:
                                        pos: self.pos
                                        size: self.size
                                        radius: [30,]
                
                Screen:
                    name: "adicionar"
                    on_enter: 
                        spinner_agenda_adicionar_colecao.values = feiras_scroll.colecoes()
                        spinner_agenda_adicionar_colecao.text = "•Escolha uma coleção"
                        spinner_agenda_adicionar_produto.text = "•Escolha um produto"
                        spinner_agenda_adicionar_subproduto.text = "•Escolha um subproduto"
                        quantidade_subproduto_agenda_adicionar.text = ""
                        descricao_agenda_adicionar.text = ""
                    
                    BoxLayout:
                        orientation: "vertical"
                        BoxLayout:
                            size_hint_y: 0.85
                            orientation: "vertical"
                            padding: 30
                            spacing: 15
                            BoxLayout:
                                size_hint_y: 0.8
                                spacing: 15
                                orientation: "vertical"
                                SpinnerDropdown:
                                    id: spinner_agenda_adicionar_colecao
                                    text: "•Escolha uma coleção"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: feiras_scroll.colecoes()
                                    on_text: spinner_agenda_adicionar_produto.values = feiras_scroll.procurar_produtos(self.text)

                                SpinnerDropdown:
                                    id: spinner_agenda_adicionar_produto
                                    text: "•Escolha um produto"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    on_text: spinner_agenda_adicionar_subproduto.values = feiras_scroll.procurar_subprodutos(self.text)

                                SpinnerDropdown:
                                    id: spinner_agenda_adicionar_subproduto
                                    text: "•Escolha um subproduto"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    
                                BoxLayout:
                                    orientation: "vertical"
                                    spacing: 50
                                    TextInput:
                                        id: quantidade_subproduto_agenda_adicionar
                                        input_filter: "float"
                                        hint_text: "Quantidade"
                                        font_size: 70
                                        height: 100
                                        size_hint_y: None
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5
                                    
                                    TextInput:
                                        id: descricao_agenda_adicionar
                                        hint_text: "Descrição"
                                        halign: "center"
                                        font_size: 70
                                        height: 175
                                        size_hint_y: None
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5

                            BoxLayout:
                                size_hint_y: 0.2
                                padding: 10
                                SpinnerDropdown:
                                    id: dia_agenda_adicionar_subproduto
                                    text: "•Dia"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
                                
                                SpinnerDropdown:
                                    id: mes_agenda_adicionar_subproduto
                                    text: "•Mês"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
                                
                                SpinnerDropdown:
                                    id: ano_agenda_adicionar_subproduto
                                    text: "•Ano"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: agenda_scroll.anos
                        
                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_agenda.transition.direction = "up"
                                    gerenciador_agenda.current = "principal"
                            
                            Botao:
                                text: "Adicionar"
                                on_release: 
                                    if spinner_agenda_adicionar_subproduto.text != "•Escolha um subproduto" and dia_agenda_adicionar_subproduto.text.isnumeric() and mes_agenda_adicionar_subproduto.text.isnumeric() and ano_agenda_adicionar_subproduto.text.isnumeric() and quantidade_subproduto_agenda_adicionar.text.isnumeric(): gerenciador_agenda.current = "principal"
                                    gerenciador_agenda.transition.direction = "up"
                                    if spinner_agenda_adicionar_subproduto.text != "•Escolha um subproduto" and dia_agenda_adicionar_subproduto.text.isnumeric() and mes_agenda_adicionar_subproduto.text.isnumeric() and ano_agenda_adicionar_subproduto.text.isnumeric() and quantidade_subproduto_agenda_adicionar.text.isnumeric(): agenda_scroll.adicionar(spinner_agenda_adicionar_subproduto.text, quantidade_subproduto_agenda_adicionar.text, descricao_agenda_adicionar.text, dia_agenda_adicionar_subproduto.text, mes_agenda_adicionar_subproduto.text, ano_agenda_adicionar_subproduto.text)
                                    

                Screen:
                    name: "editar"
                    on_enter: spinner_agenda_editar_colecoes.values = feiras_scroll.colecoes()
                    BoxLayout:
                        orientation: "vertical"
                        BoxLayout:
                            size_hint_y: 0.85
                            orientation: "vertical"
                            padding: 30
                            spacing: 15
                            BoxLayout:
                                size_hint_y: 0.65
                                spacing: 15
                                orientation: "vertical"
                                SpinnerDropdown:
                                    id: spinner_agenda_editar_colecoes
                                    text: "•Escolha uma coleção"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: feiras_scroll.colecoes()
                                    on_text: spinner_agenda_editar_produto.values = feiras_scroll.procurar_produtos(self.text)
                                
                                SpinnerDropdown:
                                    id: spinner_agenda_editar_produto
                                    text: "•Escolha um produto"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    on_text: spinner_agenda_editar_subproduto.values = feiras_scroll.procurar_produtos(self.text)

                                SpinnerDropdown:
                                    id: spinner_agenda_editar_subproduto
                                    text: "•Escolha um subproduto"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    
                                BoxLayout:
                                    orientation: "vertical"
                                    spacing: 50
                                    TextInput:
                                        id: quantidade_subproduto_agenda_editar
                                        input_filter: "float"
                                        hint_text: "Quantidade"
                                        font_size: 70
                                        height: 100
                                        size_hint_y: None
                                        halign: "center"
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5
                                    
                                    TextInput:
                                        id: descricao_agenda_editar
                                        hint_text: "Descrição"
                                        halign: "center"
                                        font_size: 70
                                        height: 100
                                        size_hint_y: None
                                        background_color: 0, 0, 0, 0
                                        canvas.before:
                                            Color:
                                                rgba: 0, 0, 0, 1
                                            Line:
                                                rectangle: (self.x, self.y, self.width, self.height)
                                                width: 5

                            BoxLayout:
                                size_hint_y: 0.35
                                padding: 10
                                SpinnerDropdown:
                                    id: dia_agenda_editar_subproduto
                                    text: "•Dia"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31']
                                
                                SpinnerDropdown:
                                    id: mes_agenda_editar_subproduto
                                    text: "•Mês"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']
                                
                                SpinnerDropdown:
                                    id: ano_agenda_editar_subproduto
                                    text: "•Ano"
                                    background_color: 0, 0, 0, 0
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    values: agenda_scroll.anos

                        BoxLayout:
                            size_hint_y: 0.15
                            Button:
                                text: "Voltar"
                                bold: True
                                font_size: 80
                                color: 0, 0, 0, 1
                                background_color: 0, 0, 0, 0
                                on_release: 
                                    gerenciador_agenda.current = "principal"
                                    gerenciador_agenda.transition.direction = "up"
                            
                            Botao:
                                text: "Excluir"
                                on_release: 
                                    agenda_scroll.excluir()
                                    gerenciador_agenda.current = "principal"
                                    gerenciador_agenda.transition.direction = "up"

                            Botao:
                                text: "Concluir"
                                on_release: 
                                    if dia_agenda_editar_subproduto.text.isnumeric() and mes_agenda_editar_subproduto.text.isnumeric() and ano_agenda_editar_subproduto.text.isnumeric() and quantidade_subproduto_agenda_editar.text.isnumeric(): gerenciador_agenda.current = "principal"
                                    if dia_agenda_editar_subproduto.text.isnumeric() and mes_agenda_editar_subproduto.text.isnumeric() and ano_agenda_editar_subproduto.text.isnumeric() and quantidade_subproduto_agenda_editar.text.isnumeric():agenda_scroll.editar(spinner_agenda_editar_subproduto.text, quantidade_subproduto_agenda_editar.text, descricao_agenda_editar.text, dia_agenda_editar_subproduto.text, mes_agenda_editar_subproduto.text, ano_agenda_editar_subproduto.text)
                                    gerenciador_agenda.transition.direction = "up"

                Screen:
                    name: "concluir"
                    on_enter:
                        preco_subproduto_compromisso_saber_mais.text = ""
                        spinner_agenda_concluir_venda_pagamento.text = "•Forma de pagamento"
                    
                    BoxLayout:
                        spacing: 10
                        orientation: "vertical"
                        BoxLayout:
                            padding: 30
                            size_hint_y: 0.45
                            spacing: 15
                            BoxLayout:
                                size_hint_x: .5
                                AsyncImage:
                                    id: imagem_compromisso_saber_mais
                                    source: ""
                                    allow_stretch: True
                                    center: self.parent.center
                            
                            BoxLayout:
                                size_hint_x: 0.5
                                orientation: "vertical"
                                Label:
                                    id: data_compromisso_saber_mais
                                    bold: True
                                    text: ""
                                    font_size: 70
                                    color: 0, 0, 0, 1

                                Label:
                                    id: nome_e_quantidade_subproduto_compromisso_saber_mais
                                    bold: True
                                    text: ""
                                    font_size: 70
                                    color: 0, 0, 0, 1
                                    
                        BoxLayout:
                            padding: 30
                            size_hint_y: .3
                            spacing: 15
                            orientation: "vertical"
                            TextInput:
                                id: preco_subproduto_compromisso_saber_mais
                                input_filter: "float"
                                font_size: 70
                                height: 100
                                halign: "center"
                                input_filter: "float"
                                size_hint_y: None
                                text: ""
                                background_color: 0, 0, 0, 0
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 0, 1
                                    Line:
                                        rectangle: (self.x, self.y, self.width, self.height)
                                        width: 5

                            SpinnerDropdown:
                                size_hint_y: 0.3
                                id: spinner_agenda_concluir_venda_pagamento
                                background_color: 0, 0, 0, 0
                                font_size: 70
                                color: 0, 0, 0, 1
                                text: "•Forma de pagamento"
                                values: ["Pix", "Dinheiro físico", "Cartão de crédito", "Cartão de débito"]

                        BoxLayout:
                            size_hint_y: 0.15
                            Botao:
                                text: "Voltar"
                                on_release: 
                                    gerenciador_agenda.current = "principal"
                                    gerenciador_agenda.transition.direction = "up"
                            
                            Botao:
                                text: "Concluir"
                                on_release: 
                                    if spinner_agenda_concluir_venda_pagamento.text != "•Forma de pagamento": agenda_scroll.adicionar_historico(spinner_agenda_concluir_venda_pagamento.text, preco_subproduto_compromisso_saber_mais.text, preco_subproduto_compromisso_saber_mais.hint_text)
                                    if spinner_agenda_concluir_venda_pagamento.text != "•Forma de pagamento": gerenciador_agenda.current = "principal"
                                    gerenciador_agenda.transition.direction = "up"


        Screen:
            name: "historico"
            BoxLayout:
                orientation: "vertical"
                spacing: 5
                BoxLayout:
                    size_hint_y: 0.15
                    padding: 30
                    spacing: 30
                    BoxLayout:
                        background_color: 1, 36/255, 148/255, 1
                        canvas:
                            Color:
                                rgba: self.background_color
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        Button:
                            id: botao_produtos_historico
                            background_color: 0, 0, 0, 0
                            on_release:
                                gerenciador_historico.transition.direction = "right"
                                gerenciador_historico.current = "historico_vendas"
                                self.parent.background_color = 1, 36/255, 148/255, 1
                                botao_feiras_historico.parent.background_color = 0, 0, 0, 0.1
                            size_hint_x: None
                            size_hint_y: None
                            height: self.parent.height
                            width: self.parent.width
                            Image:
                                id: imagem_produtos_historico
                                source: "imagens/logo.png"
                                allow_stretch: True
                                size_hint_y: None
                                size_hint_x: None
                                size: self.parent.height, self.parent.height
                                center: self.parent.center
                            
                    BoxLayout:
                        background_color: 0, 0, 0, 0.1
                        canvas:
                            Color:
                                rgba: self.background_color
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        Button:
                            id: botao_feiras_historico
                            background_color: 0, 0, 0, 0
                            on_release: 
                                gerenciador_historico.transition.direction = "left"
                                gerenciador_historico.current = "historico_feiras"
                                botao_produtos_historico.parent.background_color = 0, 0, 0, 0.1
                                self.parent.background_color = 1, 36/255, 148/255, 1
                            size_hint_x: None
                            size_hint_y: None
                            height: self.parent.height
                            width: self.parent.width
                            Image:
                                id: imagem_feiras_historico
                                source: "imagens/feiras.png"
                                allow_stretch: True
                                size_hint_y: None
                                size_hint_x: None
                                size: self.parent.height - 10, self.parent.height -10
                                center: self.parent.center

                BoxLayout:
                    orientation: "horizontal"
                    size_hint_y: 0.1
                    height: 50
                    spacing: 20
                    padding: 10
                    Label:
                        text: "Filtrar por:"
                        color: 0, 0, 0, 1
                        font_size: 60
                        
                    SpinnerDropdown:
                        id: filtro_mes_historico
                        text: "Mês: Todos"
                        background_color: 0, 0, 0, 0
                        font_size: 60
                        color: 0, 0, 0, 1
                        on_text: 
                            historico_scroll.filtro_atualizar(self.text[5:], filtro_ano_historico.text[5:])
                            historico_feiras_scroll.filtro_atualizar(self.text[5:], filtro_ano_historico.text[5:])
                        values: historico_scroll.meses_filtro()

                    SpinnerDropdown:
                        id: filtro_ano_historico
                        text: "Ano: Todos"
                        values: historico_scroll.anos_filtro()
                        font_size: 60
                        background_color: 0, 0, 0, 0
                        color: 0, 0, 0, 1
                        on_text: 
                            historico_scroll.filtro_atualizar(filtro_mes_historico.text[5:], self.text[5:])
                            historico_feiras_scroll.filtro_atualizar(filtro_mes_historico.text[5:], self.text[5:])
                                    
                            
                BoxLayout:
                    size_hint_y: 0.75
                    ScreenManager:
                        id: gerenciador_historico
                        Screen:
                            name: "historico_vendas"
                            ScrollView:
                                bar_color: 0, 0, 0, 0
                                Historico_scroll:
                                    id: historico_scroll
                                    orientation: "vertical"
                                    size_hint_y: None
                                    height: self.minimum_height
                                    padding: 30
                                    spacing: 30

                        Screen:
                            name: "historico_feiras"
                            ScrollView:
                                bar_color: 0, 0, 0, 0
                                Historico_scroll_feiras:
                                    id: historico_feiras_scroll
                                    orientation: "vertical"
                                    size_hint_y: None
                                    height: self.minimum_height
                                    padding: 30
                                    spacing: 30

        Screen:
            name: "financas"
            BoxLayout:
                orientation: "vertical"
                BoxLayout:
                    size_hint_y: 0.15
                    padding: 30
                    spacing: 15
                    BoxLayout:
                        background_color: 1, 36/255, 148/255, 1
                        canvas:
                            Color:
                                rgba: self.background_color
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        Button:
                            id: botao_financas
                            background_color: 0, 0, 0, 0
                            on_release:
                                gerenciador_financas.transition.direction = "right"
                                gerenciador_financas.current = "financas atual"
                                self.parent.background_color = 1, 36/255, 148/255, 1
                                botao_financas_historico.parent.background_color = 0, 0, 0, 0.1
                                scroll_financas_atual.atualizar()
                            size_hint_x: None
                            size_hint_y: None
                            height: self.parent.height
                            width: self.parent.width
                            AsyncImage:
                                id: imagem_produtos_historico
                                source: "imagens/logo.png"
                                allow_stretch: True
                                size_hint_y: None
                                size_hint_x: None
                                size: self.parent.height, self.parent.height
                                center: self.parent.center
                            
                    BoxLayout:
                        background_color: 0, 0, 0, 0.1
                        canvas:
                            Color:
                                rgba: self.background_color
                            Rectangle:
                                pos: self.pos
                                size: self.size
                        Button:
                            id: botao_financas_historico
                            background_color: 0, 0, 0, 0
                            on_release: 
                                gerenciador_financas.transition.direction = "left"
                                gerenciador_financas.current = "financas historico"
                                botao_financas.parent.background_color = 0, 0, 0, 0.1
                                self.parent.background_color = 1, 36/255, 148/255, 1
                                scroll_financas_historico.atualizar()
                            size_hint_x: None
                            size_hint_y: None
                            height: self.parent.height
                            width: self.parent.width
                            AsyncImage:
                                id: imagem_feiras_historico
                                source: "imagens/historico.png"
                                allow_stretch: True
                                size_hint_y: None
                                size_hint_x: None
                                size: self.parent.height - 10, self.parent.height -10
                                center: self.parent.center

                BoxLayout:
                    ScreenManager:
                        id: gerenciador_financas
                        Screen:
                            name: "financas atual"
                            ScreenManager: 
                                id: gerenciador_financas_atual
                                Screen:
                                    name: "financas atual principal"
                                    ScrollView:
                                        Scroll_financas_atual:
                                            id: scroll_financas_atual
                                            orientation: "vertical"
                                            size_hint_y: None
                                            height: self.minimum_height
                                            padding: 30
                                            spacing: 30

                                            Button:
                                                size_hint_y: None
                                                height: 150
                                                canvas.before:
                                                    Color:
                                                        rgba: (1, 74 / 255, 167 / 255, 1)
                                                    RoundedRectangle:
                                                        pos: self.pos
                                                        size: self.size
                                                        radius: [30,]
                                                
                                                on_release: 
                                                    gerenciador_financas_atual.current = "financas atual adicionando"
                                                    gerenciador_financas_atual.transition.direction = "down"
                                                background_color: 0, 0, 0, 0
                                                text: "+"
                                                bold: True
                                                font_size: 120

                                            BoxLayout:
                                                height: 150
                                                size_hint_y: None
                                                BoxLayout:
                                                    size_hint_x: .25
                                                Button:
                                                    size_hint_x: .5
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: (1, 74 / 255, 167 / 255, 1)
                                                        RoundedRectangle:
                                                            pos: self.pos
                                                            size: self.size
                                                            radius: [30,]
                                                    text: "Concluir mês"
                                                    color: 1, 1, 1, 1
                                                    bold: True
                                                    font_size: 80
                                                    on_release: scroll_financas_atual.concluir_mes()

                                                BoxLayout:
                                                    size_hint_x: .25

                                Screen:
                                    name: "financas atual adicionando"
                                    on_enter:
                                        produto_financas_adicionando.text = ""
                                        local_financas_adicionando.text = ""
                                        preco_financas_adicionando.text = ""
                                        forma_pagamento_financas_adicionando.text = "•Forma de pagamento"
                                        dia_financas_adicionando.text = scroll_financas_atual.dia_atual
                                        mes_financas_adicionando.text = scroll_financas_atual.mes_atual
                                        ano_financas_adicionando.text = scroll_financas_atual.ano_atual
                                        descricao_financas_adicionando.text = ""
                                    BoxLayout:
                                        orientation: "vertical"
                                        BoxLayout:
                                            size_hint_y: 0.85
                                            padding: 50
                                            BoxLayout:
                                                orientation: "vertical"
                                                spacing: 40
                                                TextInput:
                                                    id: produto_financas_adicionando
                                                    hint_text: "Produto"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    halign: "center"
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                TextInput:
                                                    id: local_financas_adicionando
                                                    hint_text: "Local ou loja"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    halign: "center"
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                TextInput:
                                                    id: preco_financas_adicionando
                                                    hint_text: "Preço pago"
                                                    halign: "center"
                                                    input_filter: "float" 
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                SpinnerDropdown:
                                                    id: forma_pagamento_financas_adicionando
                                                    text: "•Forma de pagamento"
                                                    background_color: 0, 0, 0, 0
                                                    color: 0, 0, 0, 1
                                                    font_size: 70
                                                    values: ["Pix", "Dinheiro físico", "Cartão de crédito", "Cartão de débito"]

                                                BoxLayout:
                                                    SpinnerDropdown:
                                                        id: dia_financas_adicionando
                                                        text: scroll_financas_atual.dia_atual
                                                        color: 0, 0, 0, 1
                                                        background_color: 0, 0, 0, 0
                                                        font_size: 70
                                                        values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"]

                                                    SpinnerDropdown:
                                                        id: mes_financas_adicionando
                                                        text: scroll_financas_atual.mes_atual
                                                        background_color: 0, 0, 0, 0
                                                        color: 0, 0, 0, 1
                                                        font_size: 70
                                                        values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]

                                                    SpinnerDropdown:
                                                        id: ano_financas_adicionando
                                                        text: scroll_financas_atual.ano_atual
                                                        background_color: 0, 0, 0, 0
                                                        color: 0, 0, 0, 1
                                                        font_size: 70
                                                        values: agenda_scroll.anos

                                                TextInput:
                                                    id: descricao_financas_adicionando
                                                    hint_text: "Descrição"
                                                    halign: "center"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5
                                        
                                        BoxLayout:
                                            size_hint_y: 0.15
                                            Botao:
                                                text: "Voltar"
                                                on_release:
                                                    gerenciador_financas_atual.current = "financas atual principal"
                                                    gerenciador_financas_atual.transition.direction = "up"
                                            
                                            Botao:
                                                text: "Adicionar"
                                                on_release:
                                                    if produto_financas_adicionando.text != "" and local_financas_adicionando.text != "" and preco_financas_adicionando.text != "" and forma_pagamento_financas_adicionando.text != "•Forma de pagamento": gerenciador_financas_atual.current = "financas atual principal" 
                                                    gerenciador_financas_atual.transition.direction = "up"
                                                    if produto_financas_adicionando.text != "" and local_financas_adicionando.text != "" and preco_financas_adicionando.text != "" and forma_pagamento_financas_adicionando.text != "•Forma de pagamento": scroll_financas_atual.adicionar(produto_financas_adicionando.text, local_financas_adicionando.text, preco_financas_adicionando.text, forma_pagamento_financas_adicionando.text, dia_financas_adicionando.text, mes_financas_adicionando.text, ano_financas_adicionando.text, descricao_financas_adicionando.text)
                                                        

                                Screen:
                                    name: "financas atual editando"
                                    BoxLayout:
                                        orientation: "vertical"
                                        BoxLayout:
                                            size_hint_y: 0.85
                                            padding: 50
                                            BoxLayout:
                                                orientation: "vertical"
                                                spacing: 40
                                                TextInput:
                                                    id: produto_financas_editando
                                                    text: "Produto"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    halign: "center"
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                TextInput:
                                                    id: local_financas_editando
                                                    text: "Local ou loja"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    halign: "center"
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                TextInput:
                                                    id: preco_financas_editando
                                                    text: "Preço pago"
                                                    halign: "center"
                                                    input_filter: "float" 
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                                SpinnerDropdown:
                                                    id: forma_pagamento_financas_editando
                                                    text: "•Forma de pagamento"
                                                    background_color: 0, 0, 0, 0
                                                    color: 0, 0, 0, 1
                                                    font_size: 70
                                                    values: ["Pix", "Dinheiro físico", "Cartão de crédito", "Cartão de débito"]

                                                BoxLayout:
                                                    SpinnerDropdown:
                                                        id: dia_financas_editando
                                                        text: scroll_financas_atual.dia_atual
                                                        color: 0, 0, 0, 1
                                                        background_color: 0, 0, 0, 0
                                                        font_size: 70
                                                        values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"]

                                                    SpinnerDropdown:
                                                        id: mes_financas_editando
                                                        text: scroll_financas_atual.mes_atual
                                                        background_color: 0, 0, 0, 0
                                                        color: 0, 0, 0, 1
                                                        font_size: 70
                                                        values: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]

                                                    SpinnerDropdown:
                                                        id: ano_financas_editando
                                                        text: scroll_financas_atual.ano_atual
                                                        background_color: 0, 0, 0, 0
                                                        color: 0, 0, 0, 1
                                                        font_size: 70
                                                        values: agenda_scroll.anos

                                                TextInput:
                                                    id: descricao_financas_editando
                                                    text: "Descrição"
                                                    halign: "center"
                                                    font_size: 70
                                                    height: 100
                                                    size_hint_y: None
                                                    background_color: 0, 0, 0, 0
                                                    canvas.before:
                                                        Color:
                                                            rgba: 0, 0, 0, 1
                                                        Line:
                                                            rectangle: (self.x, self.y, self.width, self.height)
                                                            width: 5

                                        BoxLayout:
                                            size_hint_y: 0.15
                                            Botao:
                                                text: "Voltar"
                                                on_release:
                                                    gerenciador_financas_atual.current = "financas atual principal"
                                                    gerenciador_financas_atual.transition.direction = "up"

                                            Botao:
                                                text: "Excluir"
                                                on_release:
                                                    gerenciador_financas_atual.current = "financas atual principal"
                                                    gerenciador_financas_atual.transition.direction = "up"
                                                    scroll_financas_atual.excluir()
                                            
                                            Botao:
                                                text: "Concluir"
                                                on_release:
                                                    if produto_financas_editando.text != "" and local_financas_editando.text != "" and preco_financas_editando.text != "" and forma_pagamento_financas_editando.text != "•Forma de pagamento": gerenciador_financas_atual.current = "financas atual principal"
                                                    gerenciador_financas_atual.transition.direction = "up"
                                                    if produto_financas_editando.text != "" and local_financas_editando.text != "" and preco_financas_editando.text != "" and forma_pagamento_financas_editando.text != "•Forma de pagamento": scroll_financas_atual.editar(produto_financas_editando.text, local_financas_editando.text, preco_financas_editando.text, forma_pagamento_financas_editando.text, dia_financas_editando.text, mes_financas_editando.text, ano_financas_editando.text, descricao_financas_editando.text)


                        Screen:
                            on_enter: 
                                filtro_mes_financas.values = scroll_financas_historico.meses_filtro()
                                filtro_ano_financas.values = scroll_financas_historico.anos_filtro()
                            name: "financas historico"
                            BoxLayout:
                                orientation: "vertical"
                                BoxLayout:
                                    orientation: "horizontal"
                                    size_hint_y: 0.1
                                    height: 50
                                    spacing: 20
                                    padding: 10
                                    Label:
                                        text: "Filtrar por:"
                                        color: 0, 0, 0, 1
                                        font_size: 60
                                        
                                    SpinnerDropdown:
                                        id: filtro_mes_financas
                                        text: "Mês: Todos"
                                        background_color: 0, 0, 0, 0
                                        font_size: 60
                                        color: 0, 0, 0, 1
                                        on_text: 
                                            scroll_financas_historico.filtro_atualizar(self.text[5:], filtro_ano_financas.text[5:])
                                        values: scroll_financas_historico.meses_filtro()

                                    SpinnerDropdown:
                                        id: filtro_ano_financas
                                        text: "Ano: Todos"
                                        font_size: 60
                                        values: scroll_financas_historico.anos_filtro()
                                        background_color: 0, 0, 0, 0
                                        color: 0, 0, 0, 1
                                        on_text: 
                                            scroll_financas_historico.filtro_atualizar( filtro_mes_financas.text[5:], self.text[5:])
                                ScrollView:
                                    size_hint_y: 0.9
                                    Scroll_financas_historico:
                                        id: scroll_financas_historico
                                        orientation: "vertical"
                                        size_hint_y: None
                                        height: self.minimum_height
                                        padding: 30
                                        spacing: 30

    BoxLayout:
        size_hint_y: 0.1
        spacing: 20
        BoxLayout:
            padding: 5
            Image: 
                allow_stretch: True
                source: "imagens/menu.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    on_release: 
                        gerenciador_telas_principal.transition.direction = "right"
                        gerenciador_telas_principal.current = "menu"
                        menu_proximas_entregas.atualizar()
                        menu_proximas_feiras.atualizar()
                        app.root.resetar_screenmanagers()
            
        BoxLayout:
            padding: 5
            Image:
                allow_stretch: True
                source: "imagens/estoque.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    on_release: 
                        if gerenciador_telas_principal.current == "menu": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "feiras": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "agenda": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "historico": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "financas": gerenciador_telas_principal.transition.direction = "right"
                        gerenciador_telas_principal.current = "estoque"
                        scroll_colecoes.atualizar()
                        app.root.resetar_screenmanagers()
            
        BoxLayout:
            padding: 5
            Image:
                allow_stretch: True
                source: "imagens/feiras.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    on_release: 
                        if gerenciador_telas_principal.current == "menu": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "estoque": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "agenda": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "historico": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "financas": gerenciador_telas_principal.transition.direction = "right"
                        gerenciador_telas_principal.current = "feiras"
                        feiras_scroll.atualizar()
                        app.root.resetar_screenmanagers()
            
        BoxLayout:
            padding: 5
            Image:
                allow_stretch: True
                source: "imagens/agenda.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    on_release: 
                        if gerenciador_telas_principal.current == "menu": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "estoque": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "feiras": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "historico": gerenciador_telas_principal.transition.direction = "right"
                        if gerenciador_telas_principal.current == "financas": gerenciador_telas_principal.transition.direction = "right"
                        gerenciador_telas_principal.current = "agenda"
                        agenda_scroll.atualizar()
                        app.root.resetar_screenmanagers()
            
        BoxLayout:
            padding: 5
            Image:
                allow_stretch: True
                source: "imagens/historico.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    background_color: 0, 0, 0, 0
                    on_release: 
                        if gerenciador_telas_principal.current == "menu": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "estoque": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "feiras": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "agenda": gerenciador_telas_principal.transition.direction = "left"
                        if gerenciador_telas_principal.current == "financas": gerenciador_telas_principal.transition.direction = "right"
                        gerenciador_telas_principal.current = "historico"
                        historico_scroll.atualizar()
                        historico_feiras_scroll.atualizar()
                        app.root.resetar_screenmanagers()
        
        BoxLayout:
            padding: 5
            Image:
                allow_stretch: True
                source: "imagens/financas.png"
                Botao:
                    pos: self.parent.pos
                    size: self.parent.size
                    background_color: 0, 0, 0, 0
                    on_release: 
                        gerenciador_telas_principal.transition.direction = "left"
                        gerenciador_telas_principal.current = "financas"
                        scroll_financas_atual.atualizar()
                        scroll_financas_historico.atualizar()
                        app.root.resetar_screenmanagers()


<Caixa_colecao>:
    background_color: (0, 0, 0, 0)
    halign: "center"
    height: 200
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1) if self.state=='normal' else (0.9, .1, .4, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    
    bold: True
    background_color: (0, 0, 0, 0)
    color: (1, 1, 1, 1)
    font_size: 80
    on_release: 
        app.root.ids.gerenciador_colecoes.transition.direction = "down"
        app.root.ids.scroll_produtos.atualizar(self.id_colecao)
        app.root.ids.scroll_produtos.colecao_selecionada = self.id_colecao
        app.root.ids.scroll_colecoes.colecao_selecionada = self.id_colecao
        app.root.ids.gerenciador_colecoes.current = "tela produtos"
        app.root.ids.pesquisar_produtos.hint_text = "Pesquisar em " + app.conteudo["colecoes_estoque"][app.root.ids.scroll_colecoes.colecao_selecionada - 1]["colecao"]
    
    Image:
        source: "imagens/edit.png"
        size_hint: None, None
        size: self.parent.height, self.parent.height
        y: self.parent.y
        x: self.parent.x + self.parent.width - self.width

        Button:
            pos: self.parent.pos
            size: self.parent.size
            background_color: (0, 0, 0, 0)
            on_release: 
                app.root.ids.gerenciador_colecoes.transition.direction = "down"
                app.root.ids.gerenciador_colecoes.current = "editar colecoes"
                app.root.ids.editar_colecoes_texto.text = self.parent.parent.text
                app.root.ids.scroll_colecoes.editando_colecao_id = self.parent.parent.id_colecao

<Caixa_produto>:
    background_color: (0, 0, 0, 0)
    halign: "center"
    height: 250
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1) if self.state=='normal' else (0.9, .1, .4, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    
    bold: True
    background_color: (0, 0, 0, 0)
    color: (1, 1, 1, 1)
    font_size: 80
    on_release: 
        app.root.ids.gerenciador_produtos.transition.direction = "down"
        app.root.ids.scroll_subprodutos.atualizar(self.id_produto)
        app.root.ids.scroll_produtos.produto_selecionado = self.id_produto
        app.root.ids.scroll_subprodutos.produto_selecionado = self.id_produto
        app.root.ids.scroll_subprodutos.colecao_selecionada = app.root.ids.scroll_produtos.produtos[self.id_produto - 1]["id_colecao"]
        app.root.ids.gerenciador_produtos.current = "tela subprodutos"
        app.root.ids.pesquisar_subprodutos.hint_text = "Pesquisar em " + app.conteudo["produtos_estoque"][app.root.ids.scroll_produtos.produto_selecionado - 1]["produto"]
    
    Image:
        id: imagem_produto
        source: ""
        size_hint: None, None
        size: self.parent.height * .8, self.parent.height * .8
        y: self.parent.y + self.parent.height * .1
        x: self.parent.x *1.5
        Button:
            background_color: 0, 0, 0, 0
            pos: self.parent.pos
            size: self.parent.size
            on_release: app.root.copiar_imagem(self.parent)

    Image:
        source: "imagens/edit.png"
        size_hint: None, None
        size: self.parent.height, self.parent.height
        y: self.parent.y
        x: self.parent.x + self.parent.width - self.width

        Button:
            pos: self.parent.pos
            size: self.parent.size
            background_color: (0, 0, 0, 0)
            on_release: 
                app.root.ids.gerenciador_produtos.transition.direction = "down"
                app.root.ids.gerenciador_produtos.current = "editar produtos"
                app.root.ids.editar_produto_nome.text = app.root.ids.scroll_produtos.produtos[self.parent.parent.id_produto - 1]["produto"]
                app.root.ids.editar_produto_preco.text = str(app.root.ids.scroll_produtos.produtos[self.parent.parent.id_produto - 1]["preco"])
                app.root.ids.editar_produto_imagem.source = app.root.ids.scroll_produtos.produtos[self.parent.parent.id_produto - 1]["imagem"]
                app.root.ids.scroll_produtos.editando_produto_id = self.parent.parent.id_produto

<Caixa_subproduto>:
    background_color: (0, 0, 0, 0)
    halign: "center"
    height: 250
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1) if self.state=='normal' else (0.9, .1, .4, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    
    on_release: 
        app.root.ids.scroll_imagens_subprodutos.id_subproduto = self.id_subproduto
        app.root.ids.gerenciador_subprodutos.current = "imagens subprodutos"
        app.root.ids.gerenciador_subprodutos.transition.direction = "down"
        app.root.ids.scroll_imagens_subprodutos.atualizar()
    bold: True
    background_color: (0, 0, 0, 0)
    color: (1, 1, 1, 1)
    font_size: 80
    Image:
        id: imagem_produto
        source: ""
        size_hint: None, None
        size: self.parent.height * .8, self.parent.height * .8
        y: self.parent.y + self.parent.height * .1
        x: self.parent.x * 1.5
        Button:
            background_color: 0, 0, 0, 0
            pos: self.parent.pos
            size: self.parent.size
            on_release: app.root.copiar_imagem(self.parent)

    Image:
        source: "imagens/edit.png"
        size_hint: None, None
        size: self.parent.height, self.parent.height
        y: self.parent.y
        x: self.parent.x + self.parent.width - self.width

        Button:
            pos: self.parent.pos
            size: self.parent.size
            background_color: (0, 0, 0, 0)
            on_release: 
                app.root.ids.gerenciador_subprodutos.transition.direction = "down"
                app.root.ids.gerenciador_subprodutos.current = "editar subprodutos"
                app.root.ids.editar_subproduto_nome.text = app.root.ids.scroll_subprodutos.subprodutos[self.parent.parent.id_subproduto - 1]["subproduto"]
                app.root.ids.editar_subproduto_quantidade.text = str(app.root.ids.scroll_subprodutos.subprodutos[self.parent.parent.id_subproduto - 1]["quantidade"])
                app.root.ids.editar_subproduto_imagem.source = app.root.ids.scroll_subprodutos.subprodutos[self.parent.parent.id_subproduto - 1]["imagem"]
                app.root.ids.scroll_subprodutos.editando_subproduto_id = self.parent.parent.id_subproduto

<Caixa_menu_entregas>:
    orientation: "vertical"
    size_hint_x: None
    width: 600
    height: 450
    canvas.before:
        Color:
            rgba: (1, 64 / 255, 157 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    BoxLayout:
        size_hint_y: 0.7
        BoxLayout:
            size_hint_x: 0.6
            padding: 10
            AsyncImage:
                id: imagem_compromisso_menu
                source: "imagens/logo.png"
                allow_stretch: True
                center: self.parent.center
        
        BoxLayout:
            orientation: "vertical"
            Label:
                id: data_compromisso_menu
                bold: True
                halign: "center"

            Label:
                bold: True
                id: nome_e_quantidade_subproduto_compromisso_menu
                text_size: self.parent.width, None
                line_height: 0.8
                halign: "center"
                

            Label:
                bold: True
                id: preco_subproduto_compromisso_menu
                halign: "center"

<Caixa_menu_feiras>:
    orientation: "vertical"
    size_hint_x: None
    width: 700
    height: 450
    canvas.before:
        Color:
            rgba: (1, 64 / 255, 157 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    BoxLayout:
        size_hint_y: 0.7
        BoxLayout:
            size_hint_x: 0.6
            padding: 10
            AsyncImage:
                source: "imagens/feiras.png"
                allow_stretch: True
                center: self.parent.center
        
        BoxLayout:
            orientation: "vertical"
            Label:
                id: nome_feira_menu
                text_size: self.parent.width, None
                bold: True
                halign: "center"
                

            Label:
                bold: True
                id: local_feira_menu
                text_size: self.parent.width, None
                halign: "center"
                

            Label:
                bold: True
                id: data_feira_menu
                halign: "center"
                
            
    Label:
        size_hint_y: 0.2
        bold: True
        id: horarios_feira_menu
        halign: "center"

<Caixa_agenda>:
    size_hint_y: None
    height: 250
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    BoxLayout:
        BoxLayout:
            padding: 10
            size_hint_x: 0.2
            AsyncImage:
                id: imagem_agenda_caixa
                source: "imagens/logo.png"
                allow_stretch: True

        Button:
            background_color: 0, 0, 0, 0
            id: caixinha_conteudo_agenda
            orientation: "vertical"
            size_hint_x: 0.6
            on_release: 
                app.root.ids.gerenciador_agenda.current = "concluir"
                app.root.ids.gerenciador_agenda.transition.direction = "down"

                app.root.ids.agenda_scroll.mais_informacoes_agenda = self.parent.parent.id_entrega
                app.root.ids.imagem_compromisso_saber_mais.source = app.conteudo["subprodutos_estoque"][app.conteudo["agenda"][self.parent.parent.id_entrega - 1]["id_subproduto"] - 1]["imagem"]
                app.root.ids.data_compromisso_saber_mais.text = self.parent.parent.dia + "/" + self.parent.parent.mes + "/" + self.parent.parent.ano
                app.root.ids.nome_e_quantidade_subproduto_compromisso_saber_mais.text = nome_e_quantidade_subproduto_agenda_caixa.text
                app.root.ids.preco_subproduto_compromisso_saber_mais.hint_text = "Preço: " + preco_total_agenda_caixa.text[2:]

            text: data_agenda_caixa.text + "\n" + nome_e_quantidade_subproduto_agenda_caixa.text + "\n" + preco_total_agenda_caixa.text
            font_size: 45
            bold: True
            halign: "center"
            BoxLayout:
                Label:
                    id: data_agenda_caixa
                    
                    text: ""
                    font_size: self.parent.height * .2
                    bold: True

                Label:
                    id: nome_e_quantidade_subproduto_agenda_caixa
                    
                    text: ""
                    font_size: self.parent.height * .2
                    bold: True
                
                Label:
                    id: preco_total_agenda_caixa
                    
                    text: ""
                    font_size: self.parent.height * .2
                    bold: True

        BoxLayout:
            id: editar_agenda_caixa
            size_hint_x: 0.2
            Image:
                source: "imagens/edit.png"
                
                Button:
                    on_release: 
                        app.root.ids.spinner_agenda_editar_subproduto.text = self.parent.parent.parent.parent.nome_subproduto
                        app.root.ids.quantidade_subproduto_agenda_editar.text = self.parent.parent.parent.parent.quantidade
                        app.root.ids.dia_agenda_editar_subproduto.text = self.parent.parent.parent.parent.dia
                        app.root.ids.mes_agenda_editar_subproduto.text = self.parent.parent.parent.parent.mes
                        app.root.ids.ano_agenda_editar_subproduto.text = self.parent.parent.parent.parent.ano
                        app.root.ids.descricao_agenda_editar.text = self.parent.parent.parent.parent.descricao

                        app.root.ids.agenda_scroll.editando_agenda = self.parent.parent.parent.parent.id_entrega
                        app.root.ids.gerenciador_agenda.current = "editar"
                        app.root.ids.gerenciador_agenda.transition.direction = "down"
                    pos: self.parent.pos
                    background_color: 0, 0, 0, 0
                    size: self.parent.size

<Caixa_feira>:
    spacing: 20
    padding: 20
    size_hint_y: None
    height: (len(self.children) - 1) * 200 + (len(self.children) - 2) * self.spacing + 450
    orientation: "vertical"

    BoxLayout:
        id: caixa_feira
        size_hint_y: None
        height: 400
        canvas.before:
            Color:
                rgba: (1, 74 / 255, 167 / 255, 1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [30,]

        Image:
            size_hint_x: 0.25
            source: "imagens/feiras.png"

        Botao:
            id: botao_feira_concluir
            bold: True
            halign: "center"
            color: 1, 1, 1, 1
            font_size: 60
            on_release: 
                app.root.ids.feiras_scroll.finalizar_feiras = self.parent.parent.id_feira
                app.root.ids.gerenciador_feiras.current = "concluir feira"
                app.root.ids.gerenciador_feiras.transition.direction = "down"
                app.root.ids.concluir_feira_scroll.id_feira = self.parent.parent.id_feira

        Image:
            size_hint_x: 0.3
            source: "imagens/edit.png"
            allow_stretch: True
            Button:
                pos: self.parent.pos
                size: self.parent.size
                background_color: 0, 0, 0, 0
                on_release: 
                    app.root.ids.feiras_scroll.editar_feiras = self.parent.parent.parent.id_feira
                    app.root.ids.gerenciador_feiras.transition.direction = "down"
                    app.root.ids.gerenciador_feiras.current = "editar"

                    app.root.ids.nome_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["nome_feira"]
                    app.root.ids.dia_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["data_feira"][8:]
                    app.root.ids.mes_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["data_feira"][5:7]
                    app.root.ids.ano_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["data_feira"][:4]
                    app.root.ids.local_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["local_feira"]
                    app.root.ids.descricao_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["descricao"]
                    app.root.ids.horario_inicial_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["horario_inicio"]
                    app.root.ids.horario_final_feira_editar.text = app.conteudo["feiras"][self.parent.parent.parent.id_feira - 1]["horario_final"]
                    

    BoxLayout:
        height: 150
        size_hint_y: None
        BoxLayout:
            size_hint_x:.2
        Button:
            size_hint_x: .6
            center_x: self.parent.center_x
            on_release: 
                app.root.ids.gerenciador_feiras.transition.direction = "down"
                app.root.ids.gerenciador_feiras.current = "adicionar subproduto"
                app.root.ids.feiras_scroll.adicionando_subproduto = self.parent.parent.id_feira
            bold: True
            
            text: "+"
            background_color: (0, 0, 0, 0)
            color: (1, 1, 1, 1)
            font_size: 120
            canvas.before:
                Color:
                    rgba: (1, .29, .655, 1) if self.state=='normal' else (.9, .1, .4, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [30,]
        BoxLayout:
            size_hint_x:.2

<Caixa_subproduto_feira>:
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]

    width: (app.width) * .7
    height: 200
    size_hint_y: None
    pos_hint: {'center_x':0.5}
    BoxLayout:
        size_hint_x: .02

    Image:
        size_hint_x: .3
        id: imagem_subproduto_feira
        height: self.parent.height * .8
    
    Label:
        id: texto_subproduto_feira
        size_hint_x: .48
        halign: "center"
        bold: True
        font_size: 60
    
    Button:
        size_hint_x: .2
        font_size: 80
        text: "x"
        bold: True
        color: 1, 1, 1, 1
        background_color: 0, 0, 0, 0
        on_release: 
            app.root.ids.feiras_scroll.excluir_subproduto_feira(self.parent.id)

<Caixa_concluir_feira>:
    size_hint_y: None
    height: 200

    BoxLayout:
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: (1, 74 / 255, 167 / 255, 1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [30,]
        BoxLayout:
            BoxLayout:
                padding: 10
                size_hint_x: 0.2
                AsyncImage:
                    id: imagem_feiras_subproduto_concluir
                    source: "imagens/logo.png"
                    allow_stretch: True

            BoxLayout:
                id: caixinha_descricao_concluir
                size_hint_x: 0.6
                orientation: "vertical"
                bold: True
                font_size: 60
                Label:
                    id: feiras_nome_subproduto_concluir
                    text: ""
                    
                    font_size: 60
                    bold: True

                Label:
                    id: feiras_quantidade_subproduto_concluir
                    
                    text: ""
                    font_size: 60
                    bold: True
                
                Label:
                    id: preco_total_agenda_caixa_concluir
                    
                    text: ""
                    font_size: 60
                    bold: True

            Button:
                size_hint_x: 0.2
                background_color: 0, 0, 0, 0
                on_release: 
                    app.root.ids.concluir_feira_scroll.excluir_venda_feira(self.parent.parent.parent.id)
                text: "x"
                color: 1, 1, 1, 1
                font_size: 80
                bold: True
    

<Caixa_historico>:
    size_hint_y: None
    height: 250
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    
    BoxLayout:
        BoxLayout:
            padding: 10
            size_hint_x: 0.2
            AsyncImage:
                id: imagem_historico_caixa
                source: "imagens/logo.png"
                allow_stretch: True
                size: self.parent.size

        BoxLayout:
            background_color: 0, 0, 0, 0
            id: caixinha_conteudo_historico
            orientation: "vertical"
            size_hint_x: 0.6
            Label:
                id: data_historico_caixa
                text: ""
                font_size: 60
                
                bold: True

            Label:
                id: nome_e_quantidade_subproduto_historico_caixa
                text: ""
                font_size: 60
                
                bold: True
            
            Label:
                id: preco_total_historico_caixa
                text: ""
                font_size: 60
                
                bold: True
            
            Label:
                id: metodo_de_pagamento
                
                text: ""
                font_size: 60
                bold: True

        BoxLayout:
            size_hint_x: 0.2

<Caixa_historico_feira>:
    size_hint_y: None
    height: 300
    orientation: "vertical"
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]
    BoxLayout:
        BoxLayout:
            padding: 10
            size_hint_x: 0.2
            AsyncImage:
                id: imagem_agenda_caixa
                source: "imagens/feiras.png"
                allow_stretch: True

        BoxLayout:
            id: caixa_historico_feira_textos
            orientation: "vertical"
            size_hint_x: 0.6
            Label:
                id: nome_feira_historico
                
                text: ""
                font_size: 60
                bold: True

            Label:
                id: local_feira_historico
                
                text: ""
                font_size: 60
                bold: True
            
            Label:
                id: data_feira_historico
                
                text: ""
                font_size: 60
                bold: True
            
            Label:
                id: horarios_feira_historico
                
                text: ""
                font_size: 60
                bold: True
            
            Label:
                id: preco_feiras_total_historico
                
                text: ""
                font_size: 60
                bold: True

        BoxLayout:
            size_hint_x: 0.2

<Produto_feiras_historico>:
    size_hint_y: None
    height: 250

    BoxLayout:
        size_hint_x: 0.1

    BoxLayout:
        size_hint_x: 0.8
        orientation: "vertical"
        canvas.before:
            Color:
                rgba: (1, 74 / 255, 167 / 255, 1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [30,]
        BoxLayout:
            BoxLayout:
                padding: 10
                size_hint_x: 0.2
                AsyncImage:
                    id: imagem_feiras_produto_historico
                    source: "imagens/logo.png"
                    allow_stretch: True

            BoxLayout:
                size_hint_x: 0.6
                id: caixa_historico_feira_textos
                orientation: "vertical"
                Label:
                    id: feiras_nome_subproduto_historico
                    
                    text: ""
                    font_size: 60
                    bold: True

                Label:
                    id: feiras_quantidade_produto_historico
                    
                    text: ""
                    font_size: 60
                    bold: True
                
                Label:
                    id: preco_total_feira_historico
                    
                    text: ""
                    font_size: 60
                    bold: True
                
                Label:
                    id: metodo_de_pagamento_historico_feira_produto
                    
                    text: ""
                    font_size: 60
                    bold: True

            Button:
                size_hint_x: 0.2
                background_color: 0, 0, 0, 0
    
    BoxLayout:
        size_hint_x: 0.1

<Caixa_financas_atual>:
    size_hint_y: None
    height: 300
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]

    BoxLayout:
        id: caixa_financa_descricao_atual
        orientation: "vertical"
        size_hint_x: 0.8
        Label:
            id: nome_produto
            text: ""
            font_size: 60
            bold: True
            
        
        Label:
            id: local
            text: ""
            font_size: 60
            bold: True
            
        
        Label:
            id: preco
            text: ""
            font_size: 60
            bold: True

            
        Label:
            id: data
            text: ""
            font_size: 60
            bold: True
            

    Image:
        id: editar
        size_hint_x: 0.2
        source: "imagens/edit.png"
        Button:
            on_release: 
                app.root.ids.gerenciador_financas_atual.current = "financas atual editando"
                app.root.ids.gerenciador_financas_atual.transition.direction = "down"
                app.root.ids.scroll_financas_atual.editando_financas = self.parent.parent.id

                app.root.ids.produto_financas_editando.text = self.parent.parent.nome
                app.root.ids.local_financas_editando.text = self.parent.parent.local
                app.root.ids.preco_financas_editando.text = self.parent.parent.preco
                app.root.ids.forma_pagamento_financas_editando.text = self.parent.parent.forma_pagamento
                app.root.ids.descricao_financas_editando.text = self.parent.parent.descricao

            background_color: 0, 0, 0, 0
            size_hint_x: None
            size_hint_y: None
            height: self.parent.height
            width: self.parent.width
                

<Caixa_financas_historico>:
    size_hint_y: None
    height: 250
    canvas.before:
        Color:
            rgba: (1, 74 / 255, 167 / 255, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [30,]

    BoxLayout:
        orientation: "vertical"
        id: caixa_financas_historico_textos
        Label:
            id: nome_produto
            text: ""
            font_size: self.parent.height * .2
            bold: True
            
        
        Label:
            id: local
            text: ""
            font_size: self.parent.height * .2
            bold: True
            
        
        Label:
            id: preco
            text: ""
            font_size: self.parent.height * .2
            bold: True

            
        Label:
            id: data
            text: ""
            font_size: self.parent.height * .2
            bold: True

<Caixa_imagens_subprodutos>:
    height: 500
    size_hint_y: None
    AsyncImage:
        id: imagem
        size_hint_x: 0.8
        Button:
            background_color: 0, 0, 0, 0
            pos: self.parent.pos
            size: self.parent.size
            on_release: app.root.copiar_imagem(self.parent)
    
    Button:
        size_hint_x: 0.2
        background_color: 0, 0, 0, 0
        color: 0, 0, 0, 1
        text: "x"
        font_size: 120
        bold: True
        on_release: app.root.ids.scroll_imagens_subprodutos.excluir(self.parent.id)
#